FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install torch==2.2.0+cu118 \
    torchvision==0.17.0+cu118 \
    torchaudio --index-url https://download.pytorch.org/whl/cu118

RUN pip3 install tensorboard

WORKDIR /workspace
COPY . /workspace

RUN pip3 install -r requirements.txt

EXPOSE 6006

CMD ["bash", "-c", "python3 ./team_code/dev_trainer.py --epochs $EPOCHS --batch_size $BATCH_SIZE --learning_rate $LEARNING_RATE && tensorboard --logdir=./runs --host 0.0.0.0"]
